### ISSUE TITLE
NFC Support?

### ISSUE THREAD

**Issue by sightama** [matrix-io/matrix-creator-nfc-unstable-preview#4]
Hey guys,

I really enjoy the Matrix Creator product, and appreciate the depth of available code examples and documentation. A big part of the reason I acquired this board is for its multi-functionality which includes an NFC reader, which I can't for the love of me get to work. Any ideas?

The problem I'm having occurs when I run sudo ./start_nfc.sh, for both the NXP and neardal methods.

I get these messages:
"Can't find the description for a cable named matrix_pi"
Known cables......

.....

Error: 2:GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.neard was not provided by any .service files

Any help would be greatly appreciated, as the capabilities of a working NFC reader would be wonderful.

Bonus noise: Using the NFC reader to give guests wifi configuration info ie: ssid+pass.

**Comment by sightama** [comment]
I was able to fix this by modifying the start_nfc.sh script to utilize 'matrix_creator' instead of matrix_pi as a fix, AND you need to modify stop_nfc.sh directory of:
/usr/share/admobilize/matrix....blah

to:

/usr/share/matrixlabs/matrixio-devices/fpga-blah.bash

These allow the scripts to run, but NOTHING I've done with NFC_Library or neardal has worked....


I get this error when trying to run the BasicDiscoveryLoop example, and when I try to use explore-nfc through neardal:

 ErrorInfo Comp:         PH_COMP_BAL     type:   0xbLine: 803   Error - (0x010B) has occurred : 0xCCEE CC-Component ID, EE-Error code. Refer-ph_Status.h

Any help wouldd be greatly appreciated....

**Comment by Serega280689** [comment]
Можно просто сделать Root права и переуснатовит NFC программу с обновлением и

**Comment by Hermitter** [comment]
Closing this issue. NFC support has been moved to https://github.com/matrix-io/matrix-hal-nfc
